In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
%matplotlib inline

### IMPORT DATASET

In [5]:
df=pd.read_csv("D://path//diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [6]:
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   
7           10      115              0              0        0  35.3   
8            2      197             70             45      543  30.5   
9            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [7]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [8]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [11]:
df.groupby('Pregnancies').describe()

Glucose                                                       \
              count        mean        std    min     25%    50%     75%   
Pregnancies                                                                
0             111.0  123.000000  29.408719   57.0  102.00  119.0  138.00   
1             135.0  112.748148  33.642040    0.0   91.50  109.0  129.00   
2             103.0  110.796117  26.075817   56.0   92.00  108.0  123.50   
3              75.0  123.586667  33.539849   61.0   99.00  116.0  149.00   
4              68.0  125.117647  27.686157   76.0  102.00  123.0  144.25   
5              57.0  118.859649  32.955835    0.0  103.00  116.0  139.00   
6              50.0  120.800000  34.751009    0.0  102.00  114.5  142.25   
7              45.0  136.444444  34.458510   62.0  107.00  136.0  160.00   
8              38.0  131.736842  37.772923   65.0  105.50  122.0  164.00   
9              28.0  131.392857  31.582155   57.0  112.00  132.0  156.00   
10             24.0  120.916667  28.612732   68.0  101.00  118.5  134.50   
11             11.0  126.454545  20.171086   85.0  115.50  135.0  138.00   
12              9.0  113.555556  25.219591   84.0   92.00  106.0  140.00   
13             10.0  125.500000  27.040094   76.0  106.00  127.5  150.25   
14              2.0  137.500000  53.033009  100.0  118.75  137.5  156.25   
15              1.0  136.000000        NaN  136.0  136.00  136.0  136.00   
17              1.0  163.000000        NaN  163.0  163.00  163.0  163.00   

                   BloodPressure             ...    Age       Outcome  \
               max         count       mean  ...    75%   max   count   
Pregnancies                                  ...                        
0            198.0         111.0  67.153153  ...  28.00  67.0   111.0   
1            199.0         135.0  67.792593  ...  29.00  62.0   135.0   
2            197.0         103.0  63.252427  ...  27.00  72.0   103.0   
3            193.0          75.0  66.586667  ...  31.00  63.0    75.0   
4            197.0          68.0  70.029412  ...  36.00  70.0    68.0   
5            189.0          57.0  76.210526  ...  45.00  69.0    57.0   
6            195.0          50.0  68.420000  ...  48.25  66.0    50.0   
7            196.0          45.0  70.777778  ...  43.00  61.0    45.0   
8            197.0          38.0  75.184211  ...  53.50  68.0    38.0   
9            184.0          28.0  77.892857  ...  49.00  81.0    28.0   
10           179.0          24.0  70.208333  ...  48.00  63.0    24.0   
11           155.0          11.0  74.181818  ...  50.50  51.0    11.0   
12           151.0           9.0  76.333333  ...  48.00  62.0     9.0   
13           158.0          10.0  73.800000  ...  44.75  57.0    10.0   
14           175.0           2.0  70.000000  ...  44.00  46.0     2.0   
15           136.0           1.0  70.000000  ...  43.00  43.0     1.0   
17           163.0           1.0  72.000000  ...  47.00  47.0     1.0   

                                                          
                 mean       std  min  25%  50%  75%  max  
Pregnancies                                               
0            0.342342  0.476645  0.0  0.0  0.0  1.0  1.0  
1            0.214815  0.412223  0.0  0.0  0.0  0.0  1.0  
2            0.184466  0.389760  0.0  0.0  0.0  0.0  1.0  
3            0.360000  0.483232  0.0  0.0  0.0  1.0  1.0  
4            0.338235  0.476627  0.0  0.0  0.0  1.0  1.0  
5            0.368421  0.486664  0.0  0.0  0.0  1.0  1.0  
6            0.320000  0.471212  0.0  0.0  0.0  1.0  1.0  
7            0.555556  0.502519  0.0  0.0  1.0  1.0  1.0  
8            0.578947  0.500355  0.0  0.0  1.0  1.0  1.0  
9            0.642857  0.487950  0.0  0.0  1.0  1.0  1.0  
10           0.416667  0.503610  0.0  0.0  0.0  1.0  1.0  
11           0.636364  0.504525  0.0  0.0  1.0  1.0  1.0  
12           0.444444  0.527046  0.0  0.0  0.0  1.0  1.0  
13           0.500000  0.527046  0.0  0.0  0.5  1.0  1.0  
14           1.000000  0.00

In [12]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [22]:
a = df[df['Glucose']==2]

In [23]:
a

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [24]:
b = df[df['Pregnancies']=="1"]

In [26]:
b

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

In [27]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [28]:
Test = 'Hello lets learn AI easily!!'

In [29]:
Test_punc_removed = [char for char in Test if char not in string.punctuation]
Test_punc_removed

['H',
 'e',
 'l',
 'l',
 'o',
 ' ',
 'l',
 'e',
 't',
 's',
 ' ',
 'l',
 'e',
 'a',
 'r',
 'n',
 ' ',
 'A',
 'I',
 ' ',
 'e',
 'a',
 's',
 'i',
 'l',
 'y']

In [30]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rooba\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
sample_data = ['This is the first document.','This document is the second document.','And this is the third one.','Is this the first document?']

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(sample_data)

In [34]:
print(X.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [35]:
# Define a pipeline to clean up all the messages

def message_cleaning(message):
    Test_punc_removed = [char for char in message if char not in string.punctuation]
    Test_punc_removed_join = ''.join(Test_punc_removed)
    Test_punc_removed_join_clean = [word for word in Test_punc_removed_join.split() if word.lower() not in stopwords.words('english')]
    return Test_punc_removed_join_clean

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(analyzer = message_cleaning)
countvectorizer = vectorizer.fit_transform(df['Glucose'])


In [ ]:
print(vectorizer.get_feature_names())


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [47]:
X = df.drop('Glucose', axis=1)  # Features
y = df['BloodPressure']

#### Split data into training and testing sets


In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [56]:
# Standardize features (optional but often helpful)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [57]:
# Create a machine learning model (Random Forest Classifier)
clf = RandomForestClassifier(random_state=42)
# Train the model on the training data
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [58]:
# Make predictions on the test data
y_pred = clf.predict(X_test)


In [59]:
# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(report)

Accuracy: 0.6493506493506493
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
          48       0.00      0.00      0.00         2
          50       0.00      0.00      0.00         2
          52       0.00      0.00      0.00         2
          54       0.00      0.00      0.00         1
          55       0.00      0.00      0.00         0
          56       0.40      1.00      0.57         2
          58       1.00      0.50      0.67         6
          60       0.64      0.64      0.64        11
          62       0.50      0.67      0.57         6
          64       0.55      0.86      0.67         7
          65       0.00      0.00      0.00         3
          66       0.40      0.33      0.36         6
          68       0.71      1.00      0.83         5
          70       1.00      1.00      1.00        11
          72       1.00      1.00      1.00        10
          74       0.73      

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_cla